import type { Intent } from "./types";

export const SIGNES_INTENTS: Intent[] = [
  {
    id: "signes_generaux",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "signes",
      "signe",
      "symptome*",
      "comment savoir si",
      "comment reconnaitre",
      "reconnaitre",
      "que surveiller",
      "quels signes",
      "alerte",
    ],
    reply:
      "D'après l'OMS, les principaux signes sont : une boule ou un épaississement du sein, souvent sans douleur ; un changement de taille, de forme ou d'aspect ; des fossettes, une rougeur ou d'autres changements de la peau ; un changement du mamelon ou de la peau autour ; un liquide anormal ou sanglant qui sort du mamelon. Ces signes ne veulent pas dire cancer, mais ils méritent un examen.",
    actions: [
      { label: "Voir les signes en images", href: "/signes" },
      { label: "Écouter", href: "/audio" },
      { label: "Trouver un centre", href: "/carte" },
    ],
    followUps: ["J'ai senti une boule", "Comment me palper ?", "Où me faire dépister ?"],
  },
  {
    id: "boule",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "boule",
      "boules",
      "masse",
      "nodule*",
      "grosseur*",
      "bosse*",
      "dur dans le sein",
      "epaississement",
      "induration",
      "zone dure",
      "quelque chose dans le sein",
    ],
    reply:
      "Merci de me le dire. Une boule ou un épaississement doit toujours être examiné, même s'il ne fait pas mal. La plupart des boules ne sont pas des cancers, mais seul un professionnel peut le confirmer. Et les boules cancéreuses se traitent plus facilement quand elles sont petites : mieux vaut ne pas attendre.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["Comment se passe un examen ?", "C'est gratuit ?", "Est-ce que c'est un kyste ?"],
  },
  {
    id: "peau",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "peau",
      "rougeur*",
      "peau d orange",
      "fossette*",
      "plis",
      "gonflement",
      "enflure",
    ],
    reply:
      "Des fossettes, un aspect de « peau d'orange », une rougeur ou d'autres changements de la peau du sein font partie des signes à faire vérifier. Cela peut avoir d'autres causes et ce n'est pas un diagnostic, mais mieux vaut consulter sans attendre.",
    actions: [
      { label: "Voir les signes en images", href: "/signes" },
      { label: "Trouver un centre", href: "/carte" },
    ],
    followUps: ["Où me faire dépister ?", "C'est gratuit ?"],
  },
  {
    id: "mamelon",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "mamelon*",
      "tetine*",
      "ecoulement*",
      "liquide",
      "sang",
      "suintement",
      "pus",
      "croute*",
      "aureole",
    ],
    reply:
      "Un mamelon dont l'aspect change (par exemple qui rentre alors qu'il ne le faisait pas), une peau qui pèle ou forme des croûtes autour, ou un liquide qui s'écoule, surtout s'il est sanglant, méritent un examen. Ce n'est pas forcément grave, mais ne l'ignorez pas.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["Où me faire dépister ?", "Comment se passe un examen ?"],
  },
  {
    id: "forme",
    status: "review",
    sources: ["who-bc", "quotidien"],
    keywords: [
      "forme",
      "taille",
      "plus gros",
      "plus petit",
      "asymetrie",
      "asymetrique",
      "dissymetrie",
      "change de forme",
      "volume",
      "seins pas pareils",
    ],
    reply:
      "Un sein qui change de taille, de forme ou d'aspect est un signe à faire examiner. Il est fréquent que les deux seins ne soient pas parfaitement identiques ; ce qui compte, c'est un changement récent par rapport à ce qui est habituel pour vous.",
    actions: [{ label: "Voir les signes en images", href: "/signes" }],
    followUps: ["Comment me palper ?", "Où me faire dépister ?"],
  },
  {
    id: "douleur",
    status: "review",
    sources: ["who-bc", "msd"],
    keywords: [
      "douleur*",
      "mal au sein",
      "mal aux seins",
      "sein douloureux",
      "seins douloureux",
      "fait mal au sein",
      "sein me fait mal",
      "sein fait mal",
      "seins me font mal",
      "seins font mal",
      "j ai mal",
      "mastodynie",
      "mastalgie",
      "mastose",
    ],
    reply:
      "La douleur au sein est fréquente et n'est pas, le plus souvent, liée à un cancer ; à l'inverse, une boule cancéreuse est souvent indolore. Consultez si la douleur est forte, reste au même endroit sans lien avec les règles, ou s'accompagne de rougeur, de chaleur, de gonflement ou d'un écoulement. Depuis quand avez-vous cette douleur ?",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["Où me faire dépister ?", "Est-ce que c'est un kyste ?"],
  },
  {
    id: "aisselle",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "aisselle*",
      "sous l aisselle",
      "dans l aisselle",
      "ganglion*",
      "sous le bras",
      "sous les bras",
      "axillaire*",
    ],
    reply:
      "Les ganglions sous l'aisselle sont souvent le premier endroit où un cancer du sein peut s'étendre, et il arrive qu'un ganglion atteint ne puisse pas se sentir. Une boule ou un gonflement sous l'aisselle doit donc être examiné. Il existe aussi beaucoup de causes bénignes, mais seul un professionnel peut faire la différence.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["Où me faire dépister ?", "C'est gratuit ?"],
  },
  {
    id: "plaie",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "plaie*",
      "ne guerit pas",
      "ulcere*",
      "ulceration",
      "blessure",
      "eczema du mamelon",
    ],
    reply:
      "Une plaie du sein ou du mamelon qui ne guérit pas doit être vue par un professionnel de santé, qui pourra faire une biopsie pour en connaître la cause. Une plaie n'est pas toujours douloureuse : l'absence de douleur ne doit pas vous rassurer à tort.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["C'est quoi une biopsie ?", "Où me faire dépister ?"],
  },
  {
    id: "pas_de_boule",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "pas de boule",
      "aucune boule",
      "rien senti",
      "aucun symptome",
      "pas de symptome",
      "sans symptome",
      "je ne sens rien",
      "rien du tout",
    ],
    reply:
      "Ne pas sentir de boule ne veut pas dire que tout est normal : d'autres signes existent (peau, mamelon, forme, écoulement). Et sans aucun signe, un dépistage peut être proposé selon l'âge et la situation. Le plus utile est de bien connaître vos seins pour repérer un changement.",
    actions: [{ label: "Voir les signes en images", href: "/signes" }],
    followUps: ["Comment me palper ?", "À partir de quel âge ?"],
  },
  {
    id: "benin",
    status: "sourced",
    sources: ["who-bc", "msd"],
    keywords: [
      "kyste*",
      "fibroadenome*",
      "benin*",
      "benigne*",
      "pas grave",
      "mastose*",
      "tumeur benigne",
    ],
    reply:
      "Beaucoup de grosseurs du sein sont bénignes, par exemple des kystes (poches de liquide) ou des fibroadénomes. L'OMS rappelle que la plupart des boules ne sont pas des cancers. Mais on ne peut pas le savoir en se palpant : un examen par un professionnel, parfois avec une échographie, permet de le confirmer.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["C'est quoi une échographie ?", "C'est quoi une biopsie ?"],
  },
  {
    id: "auto_examen",
    status: "review",
    sources: ["afro-bf", "who-bc"],
    keywords: [
      "auto examen",
      "autoexamen",
      "autopalpation",
      "auto palpation",
      "palper",
      "me palper",
      "comment palper",
      "comment verifier",
      "verifier mes seins",
      "examiner mes seins",
      "comment m examiner",
      "m examiner moi meme",
    ],
    reply:
      "Connaître ses seins aide à repérer un changement. Une fois par mois, quelques jours après la fin des règles : 1) regardez-vous dans un miroir, bras le long du corps puis levés ; 2) avec trois doigts à plat, faites de petits cercles sur tout le sein jusqu'à l'aisselle, debout puis allongée ; 3) observez le mamelon. Au Burkina Faso, l'autopalpation est encouragée, suivie d'un examen par un professionnel en cas de doute. Elle ne remplace pas le dépistage.",
    actions: [
      { label: "Guide pas à pas", href: "/connaitre" },
      { label: "Voir les signes en images", href: "/signes" },
    ],
    followUps: ["Quand le faire ?", "Quels sont les signes ?", "Où me faire dépister ?"],
  },
  {
    id: "quand_auto_examen",
    status: "review",
    keywords: [
      "combien de fois",
      "chaque mois",
      "une fois par mois",
      "quand me palper",
      "quand faire l auto examen",
      "quand le faire",
      "quel moment du cycle",
      "apres les regles",
      "quand m examiner",
    ],
    reply:
      "Une fois par mois suffit, à peu près au même moment du cycle : quelques jours après la fin des règles, quand les seins sont moins sensibles. Si vous n'avez plus de règles, choisissez un jour fixe du mois. L'important est la régularité, pas la perfection.",
    actions: [{ label: "Guide pas à pas", href: "/connaitre" }],
    followUps: ["Comment me palper ?", "Quels sont les signes ?"],
  },
];
