import type { Intent } from "./types";

export const SANTE_INTENTS: Intent[] = [
  {
    id: "risques",
    status: "sourced",
    sources: ["who-bc", "who-bcam"],
    keywords: [
      "risque*",
      "facteur*",
      "cause*",
      "pourquoi le cancer",
      "qui est concerne",
      "qui peut avoir",
      "a risque",
      "pourquoi moi",
      "comment ca arrive",
    ],
    reply:
      "D'après l'OMS, le risque augmente avec l'âge, l'obésité, la consommation nocive d'alcool, le tabac, les antécédents familiaux, une exposition passée à des radiations, certains éléments de l'histoire reproductive et un traitement hormonal après la ménopause. Mais environ 80 % des cancers du sein surviennent chez des femmes sans autre facteur de risque que le sexe et l'âge : toute femme est concernée.",
    followUps: ["Est-ce héréditaire ?", "Comment réduire le risque ?", "Quels sont les signes ?"],
  },
  {
    id: "famille",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "antecedent*",
      "famille",
      "familial*",
      "ma mere",
      "ma soeur",
      "ma grand mere",
      "ma tante",
      "heredit*",
      "genetique*",
      "brca*",
      "mutation*",
    ],
    reply:
      "Avoir une proche atteinte augmente le risque, mais la plupart des femmes qui ont un cancer du sein n'ont pas d'antécédent familial connu : l'absence d'antécédent ne veut donc pas dire absence de risque. Certaines mutations héréditaires (BRCA1, BRCA2, PALB2) augmentent fortement le risque. Si plusieurs proches ont été touchées, parlez-en à un professionnel de santé.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["À partir de quel âge ?", "Quels sont les risques ?"],
  },
  {
    id: "reduire",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "reduire le risque",
      "diminuer le risque",
      "reduire",
      "comment prevenir",
      "comment eviter",
      "alcool",
      "tabac",
      "fumer",
      "obesite",
      "alimentation",
      "regime",
      "sport",
    ],
    reply:
      "Vous ne pouvez pas tout contrôler, mais certains facteurs peuvent être modifiés : maintenir un poids sain, limiter l'alcool, ne pas fumer. Aucun geste ne garantit de ne pas avoir la maladie : le plus efficace reste de repérer tôt un changement et de consulter.",
    followUps: ["Quels sont les risques ?", "Comment me palper ?"],
  },
  {
    id: "hommes",
    status: "sourced",
    sources: ["who-bc"],
    keywords: ["homme*", "chez l homme", "un homme peut", "garcon*"],
    reply:
      "Oui, mais c'est rare : environ 0,5 à 1 % des cancers du sein surviennent chez des hommes, selon l'OMS. Un homme qui remarque une boule ou un changement au niveau du sein doit aussi consulter.",
    followUps: ["Quels sont les signes ?", "Où me faire dépister ?"],
  },
  {
    id: "jeune",
    status: "sourced",
    sources: ["who-bc", "who-bcam"],
    keywords: ["jeune*", "20 ans", "25 ans", "30 ans", "adolescente*"],
    reply:
      "Le cancer du sein peut survenir à tout âge après la puberté, même si le risque augmente avec l'âge. L'OMS note que dans les pays à ressources limitées, il touche souvent des femmes plus jeunes. Chez une jeune femme, la plupart des boules sont bénignes, mais toute boule ou tout changement doit être examiné.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["Comment me palper ?", "Quels sont les signes ?"],
  },
  {
    id: "grossesse_allaitement",
    status: "review",
    sources: ["msd"],
    keywords: [
      "enceinte",
      "grossesse",
      "allait*",
      "mastite",
      "bebe",
      "regles",
      "menstruation*",
      "cycle",
    ],
    reply:
      "Les seins changent beaucoup pendant les règles, la grossesse et l'allaitement : c'est normal. Mais une boule qui persiste, ou un sein rouge, chaud et douloureux avec de la fièvre (parfois une infection appelée mastite), doit être examiné rapidement. Vous pouvez en parler à une sage-femme.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["Quels sont les signes ?", "Où me faire dépister ?"],
  },
  {
    id: "mythe_malediction",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "malediction*",
      "sorcellerie",
      "sorcier*",
      "marabout*",
      "punition",
      "mauvais sort",
      "envout*",
      "chatiment",
    ],
    reply:
      "Non. Le cancer du sein est une maladie, pas une malédiction ni une punition. Il n'est causé ni par la sorcellerie ni par une faute. Comme d'autres maladies, il peut être dépisté et soigné, et les traitements sont d'autant plus efficaces qu'il est repéré tôt.",
    followUps: ["Est-ce contagieux ?", "Quels sont les risques ?"],
  },
  {
    id: "contagieux",
    status: "review",
    sources: ["who-bc"],
    keywords: ["contagieu*", "contagion", "transmissible", "attraper", "attrape*", "contamine*"],
    reply:
      "Non. Le cancer du sein n'est pas contagieux : on ne l'attrape pas au contact d'une personne malade, ni en partageant ses affaires ou en vivant avec elle.",
    followUps: ["C'est une malédiction ?", "Quels sont les risques ?"],
  },
  {
    id: "mythe_palper",
    status: "review",
    keywords: [
      "propag*",
      "toucher aggrave",
      "palper aggrave",
      "palper propage",
      "se palper dangereux",
      "aggrave*",
    ],
    reply:
      "Non. Se palper les seins ne propage pas la maladie. Au contraire, savoir ce qui est normal pour vous aide à repérer un changement tôt. Palpez avec le plat des doigts, doucement mais fermement.",
    followUps: ["Comment me palper ?", "Quand le faire ?"],
  },
  {
    id: "mythe_objets",
    status: "review",
    sources: ["who-bc"],
    keywords: [
      "deodorant*",
      "soutien gorge",
      "soutiens gorge",
      "parfum",
      "antitranspirant",
    ],
    reply:
      "Les déodorants et les soutiens-gorge ne figurent pas parmi les facteurs de risque cités par l'OMS pour le cancer du sein. Si une rumeur vous inquiète, un professionnel de santé pourra vous répondre.",
    followUps: ["Quels sont les risques ?", "Comment réduire le risque ?"],
  },
  {
    id: "guerison",
    status: "sourced",
    sources: ["who-bc", "lepays"],
    keywords: [
      "guer*",
      "curable",
      "se soigne",
      "survie",
      "survivre",
      "deces",
      "mortel*",
      "mourir",
      "meurt",
      "meurent",
      "condamne*",
      "vais je mourir",
    ],
    reply:
      "Le cancer du sein n'est pas une condamnation. L'OMS indique que la mortalité diminue quand les cas sont détectés et traités tôt, et que les traitements sont plus efficaces et mieux tolérés lorsqu'ils sont commencés tôt et menés jusqu'au bout. Je ne peux pas promettre une issue pour une personne précise, mais c'est la raison pour laquelle consulter vite compte tant.",
    actions: [{ label: "Trouver un centre", href: "/carte" }],
    followUps: ["Comment se soigne-t-il ?", "Où me faire dépister ?"],
  },
  {
    id: "traitement",
    status: "sourced",
    sources: ["who-bc"],
    keywords: [
      "traitement*",
      "chirurgie*",
      "chimio*",
      "radiotherapie",
      "operation",
      "operer",
      "mastectomie",
      "enlever le sein",
      "ablation",
      "tumorectomie",
      "comment se soigne",
    ],
    reply:
      "Le traitement dépend de la personne, du type de cancer et de son extension. Il combine en général la chirurgie (parfois seulement la tumeur, parfois le sein entier), la radiothérapie et des médicaments (hormonothérapie, chimiothérapie, thérapies ciblées). L'OMS souligne l'importance d'aller jusqu'au bout du traitement. C'est l'équipe soignante qui choisit avec vous. Si vous êtes déjà suivie, l'espace Accompagnement vous soutiendra.",
    followUps: ["C'est gratuit ?", "Parler d'une association"],
  },
  {
    id: "peur",
    status: "review",
    keywords: [
      "peur*",
      "honte",
      "j ose pas",
      "n ose pas",
      "j ai honte",
      "embarrass*",
      "mal a l aise",
      "angoisse*",
      "inquiet*",
      "anxieu*",
      "panique*",
      "terrifie*",
    ],
    reply:
      "Avoir peur ou se sentir gênée est tout à fait normal : beaucoup de femmes ressentent la même chose. Ici, personne ne vous juge. Un examen est un moment court avec des professionnels, et vous pouvez venir accompagnée. Voulez-vous que je vous explique comment se passe une consultation ?",
    followUps: ["Comment se passe un examen ?", "Où me faire dépister ?"],
  },
  {
    id: "proche",
    status: "review",
    keywords: [
      "ma mere a un cancer",
      "ma soeur a un cancer",
      "mon amie a un cancer",
      "ma maman est malade",
      "comment aider",
      "aider une proche",
      "proche malade",
    ],
    reply:
      "C'est précieux d'être là pour une proche. Écoutez sans juger, proposez de l'accompagner à ses rendez-vous, et rappelez-lui qu'elle n'est pas seule. Des associations peuvent aussi l'aider. Prenez soin de vous également.",
    actions: [{ label: "Voir les associations", href: "/association" }],
    followUps: ["Parler d'une association", "C'est gratuit ?"],
  },
];
