import type { Source, SourceId } from "./types";

/** Sources consultées le 3 octobre 2026. Les liens servent à la relecture par un professionnel. */
export const SOURCES: Record<SourceId, Source> = {
  "who-bc": {
    id: "who-bc",
    short: "OMS",
    title: "Breast cancer (fiche d'information)",
    publisher: "Organisation mondiale de la Santé",
    url: "https://www.who.int/news-room/fact-sheets/detail/breast-cancer",
    date: "2026-07-03",
    kind: "officielle",
  },
  "who-bcam": {
    id: "who-bcam",
    short: "OMS",
    title: "Breast Cancer Awareness Month 2026",
    publisher: "Organisation mondiale de la Santé",
    url: "https://www.who.int/news-room/events/detail/2026/10/01/default-calendar/breast-cancer-awareness-month-2026",
    date: "2026-10-01",
    kind: "officielle",
  },
  "afro-bf": {
    id: "afro-bf",
    short: "OMS Afrique",
    title: "Au Burkina Faso, une lutte soutenue contre le cancer du sein",
    publisher: "OMS Bureau régional de l'Afrique",
    url: "https://www.afro.who.int/fr/news/au-burkina-faso-une-lutte-soutenue-contre-le-cancer-du-sein",
    kind: "officielle",
  },
  inca: {
    id: "inca",
    short: "INCa",
    title: "Le programme de dépistage des cancers du sein en pratique",
    publisher: "Institut national du cancer (France)",
    url: "https://www.sante.fr/node/6395905",
    kind: "officielle",
  },
  sidwaya: {
    id: "sidwaya",
    short: "Sidwaya",
    title: "Cancers du sein et du col de l'utérus : la prévention par le dépistage précoce",
    publisher: "Sidwaya",
    url: "https://www.sidwaya.info/carrefour/2024/11/28/cancers-du-sein-et-du-col-de-luterus-la-prevention-par-le-depistage-precoce/",
    date: "2024-11-28",
    kind: "presse",
  },
  fasoamazone: {
    id: "fasoamazone",
    short: "FasoAmazone",
    title: "Burkina Faso : campagnes de dépistage gratuites, un espoir pour vaincre le cancer chez les femmes",
    publisher: "FasoAmazone",
    url: "https://www.fasoamazone.net/2025/12/05/",
    date: "2025-12-05",
    kind: "presse",
  },
  apidpm: {
    id: "apidpm",
    short: "Santé tropicale",
    title: "Octobre rose : « Le Burkina est sur la voie pour devenir un modèle… » (entretien avec le Pr Nayi Zongo)",
    publisher: "APIDPM Santé tropicale",
    url: "https://www.santetropicale.com/actus.asp?action=lire&id=35212",
    kind: "presse",
  },
  lepays: {
    id: "lepays",
    short: "Le Pays",
    title: "Lutte contre les cancers féminins : de la nécessité de poursuivre les efforts",
    publisher: "Le Pays (via allAfrica)",
    url: "https://fr.allafrica.com/stories/202610020122.html",
    date: "2026-10-01",
    kind: "presse",
  },
  zcf: {
    id: "zcf",
    short: "allAfrica",
    title: "Lutte contre le cancer du sein : des femmes reçoivent des prothèses mammaires",
    publisher: "allAfrica",
    url: "https://fr.allafrica.com/stories/202410210340.html",
    date: "2024-10-20",
    kind: "presse",
  },
  "sante-bf": {
    id: "sante-bf",
    short: "Ministère de la Santé",
    title: "Campagne gratuite de chirurgie du cancer du sein",
    publisher: "Ministère de la Santé et de l'Hygiène publique (Burkina Faso)",
    url: "https://sante.gov.bf",
    kind: "officielle",
  },
  msd: {
    id: "msd",
    short: "Manuels MSD",
    title: "Nodules mammaires",
    publisher: "Manuels MSD",
    url: "https://www.msdmanuals.com/fr/professional/gyn%C3%A9cologie-et-obst%C3%A9trique/troubles-du-sein/nodules-mammaires",
    kind: "reference-medicale",
  },
  quotidien: {
    id: "quotidien",
    short: "Quotidien du Médecin",
    title: "L'examen clinique des seins doit être réhabilité",
    publisher: "Le Quotidien du Médecin",
    url: "https://cardiologie.lequotidiendumedecin.fr/specialites/cancerologie/lexamen-clinique-des-seins-doit-etre-rehabilite",
    kind: "presse",
  },
  "burkina24-or": {
    id: "burkina24-or",
    short: "Burkina24",
    title: "Cancer du sein au Burkina Faso : « Trois décès par jour », le gouvernement intensifie le dépistage",
    publisher: "Burkina24",
    url: "https://burkina24.com/2026/10/03/cancer-du-sein-au-burkina-faso-trois-deces-par-jour-le-gouvernement-intensifie-le-depistage/",
    date: "2026-10-03",
    kind: "presse",
  },
  "burkina24-mt": {
    id: "burkina24-mt",
    short: "Burkina24",
    title: "Cancer du sein : le diagnostic moléculaire par la « MammaTyper », désormais disponible au Burkina Faso",
    publisher: "Burkina24",
    url: "https://burkina24.com/2026/10/02/cancer-du-sein-le-diagnostic-moleculaire-par-la-mammatyper-desormais-disponible-au-burkina-faso/",
    date: "2026-10-02",
    kind: "presse",
  },
  "minute-mt": {
    id: "minute-mt",
    short: "Minute.bf",
    title: "Cancer du sein : le diagnostic moléculaire par la « MammaTyper », désormais disponible au Burkina Faso",
    publisher: "Minute.bf",
    url: "https://www.minute.bf/cancer-du-sein-le-diagnostic-moleculaire-par-la-mammatyper-desormais-disponible-au-burkina-faso/",
    date: "2026-10-02",
    kind: "presse",
  },
    icm: {
    id: "icm",
    short: "ICM",
    title: "Ma chimiothérapie : guide pratique pour gérer les effets secondaires",
    publisher: "Institut du Cancer de Montpellier (Unicancer)",
    url: "https://icm.unicancer.fr/fr/file-download/download/public/222",
    kind: "officielle",
  },
  "gustave-roussy": {
    id: "gustave-roussy",
    short: "Gustave Roussy",
    title: "La chimiothérapie : guide d'accompagnement (2016)",
    publisher: "Gustave Roussy",
    url: "https://www.gustaveroussy.fr/sites/default/files/chimiotherapie-2016.pdf",
    date: "2016",
    kind: "officielle",
  },
  chuv: {
    id: "chuv",
    short: "CHUV",
    title: "Fiches d'information sur les traitements de chimiothérapie",
    publisher: "Centre hospitalier universitaire vaudois (Suisse)",
    url: "https://files.chuv.ch/catalog-prod-public/pdf/chuvbricks/traitement/web_trt_31/20251110-084120_web_trt_31_etoposide.pdf",
    date: "2025-11-10",
    kind: "officielle",
  },
  cusm: {
    id: "cusm",
    short: "CUSM",
    title: "Retour chez soi après la chimio",
    publisher: "Centre universitaire de santé McGill (Canada)",
    url: "https://cusm.ca/sites/default/files/micro/m-Cancer/Retour-chez-soi-apres-chimio_FR_edited_compressed.pdf",
    kind: "officielle",
  },
  hug: {
    id: "hug",
    short: "HUG",
    title: "Comment parler du cancer à mon enfant ?",
    publisher: "Hôpitaux universitaires de Genève",
    url: "https://www.hug.ch/departement-oncologie/comment-parler-cancer-mon-enfant",
    kind: "officielle",
  },
  ciusss: {
    id: "ciusss",
    short: "CIUSSS Nord-de-l'Île",
    title: "Comment parler à mon enfant et l'accompagner après mon diagnostic de cancer",
    publisher: "CIUSSS du Nord-de-l'Île-de-Montréal",
    url: "https://cdn.ciusssnordmtl.ca/Fichiers/07Usagers_Visiteurs/Fiches_usagers/NIM-DSI-FicheInfoUsager-EnfantApresDiagnosticCancer-8900935_-_FINALE.pdf",
    kind: "officielle",
  },
  "inca-image": {
    id: "inca-image",
    short: "INCa",
    title: "Women's initial experiences of their appearance after mastectomy and/or breast reconstruction (veille INCa)",
    publisher: "Institut national du cancer (France)",
    url: "https://www.cancer.fr/professionnels-de-sante/veille/nota-bene-cancer/bulletin-n-420/women-s-initial-experiences-of-their-appearance-after-mastectomy-and-or-breast-reconstruction-a-qualitative-study",
    kind: "officielle",
  },
  "inca-recon": {
    id: "inca-recon",
    short: "INCa",
    title: "Body image and quality of life of breast cancer patients: influence of timing and stage of breast reconstruction (veille INCa)",
    publisher: "Institut national du cancer (France)",
    url: "https://www.cancer.fr/professionnels-de-sante/veille/nota-bene-cancer/bulletin-n-284/body-image-and-quality-of-life-of-breast-cancer-patients-influence-of-timing-and-stage-of-breast-reconstruction",
    kind: "officielle",
  },
};
