import type { Source, SourceId } from "./types";

/** Sources consultées le 3 octobre 2026. Les liens servent à la relecture par un professionnel. */
export const SOURCES: Record<SourceId, Source> = {
  "who-bc": {
    id: "who-bc",
    short: "OMS",
    title: "Breast cancer (fiche d'information)",
    publisher: "Organisation mondiale de la Santé",
    url: "https://www.who.int/news-room/fact-sheets/detail/breast-cancer",
    date: "2026-07-03",
    kind: "officielle",
  },
  "who-bcam": {
    id: "who-bcam",
    short: "OMS",
    title: "Breast Cancer Awareness Month 2026",
    publisher: "Organisation mondiale de la Santé",
    url: "https://www.who.int/news-room/events/detail/2026/10/01/default-calendar/breast-cancer-awareness-month-2026",
    date: "2026-10-01",
    kind: "officielle",
  },
  "afro-bf": {
    id: "afro-bf",
    short: "OMS Afrique",
    title: "Au Burkina Faso, une lutte soutenue contre le cancer du sein",
    publisher: "OMS Bureau régional de l'Afrique",
    url: "https://www.afro.who.int/fr/news/au-burkina-faso-une-lutte-soutenue-contre-le-cancer-du-sein",
    kind: "officielle",
  },
  inca: {
    id: "inca",
    short: "INCa",
    title: "Le programme de dépistage des cancers du sein en pratique",
    publisher: "Institut national du cancer (France)",
    url: "https://www.sante.fr/node/6395905",
    kind: "officielle",
  },
  sidwaya: {
    id: "sidwaya",
    short: "Sidwaya",
    title: "Cancers du sein et du col de l'utérus : la prévention par le dépistage précoce",
    publisher: "Sidwaya",
    url: "https://www.sidwaya.info/carrefour/2024/11/28/cancers-du-sein-et-du-col-de-luterus-la-prevention-par-le-depistage-precoce/",
    date: "2024-11-28",
    kind: "presse",
  },
  fasoamazone: {
    id: "fasoamazone",
    short: "FasoAmazone",
    title: "Burkina Faso : campagnes de dépistage gratuites, un espoir pour vaincre le cancer chez les femmes",
    publisher: "FasoAmazone",
    url: "https://www.fasoamazone.net/2025/12/05/",
    date: "2025-12-05",
    kind: "presse",
  },
  apidpm: {
    id: "apidpm",
    short: "Santé tropicale",
    title: "Octobre rose : « Le Burkina est sur la voie pour devenir un modèle… » (entretien avec le Pr Nayi Zongo)",
    publisher: "APIDPM Santé tropicale",
    url: "https://www.santetropicale.com/actus.asp?action=lire&id=35212",
    kind: "presse",
  },
  lepays: {
    id: "lepays",
    short: "Le Pays",
    title: "Lutte contre les cancers féminins : de la nécessité de poursuivre les efforts",
    publisher: "Le Pays (via allAfrica)",
    url: "https://fr.allafrica.com/stories/202610020122.html",
    date: "2026-10-01",
    kind: "presse",
  },
  zcf: {
    id: "zcf",
    short: "allAfrica",
    title: "Lutte contre le cancer du sein : des femmes reçoivent des prothèses mammaires",
    publisher: "allAfrica",
    url: "https://fr.allafrica.com/stories/202410210340.html",
    date: "2024-10-20",
    kind: "presse",
  },
  "sante-bf": {
    id: "sante-bf",
    short: "Ministère de la Santé",
    title: "Campagne gratuite de chirurgie du cancer du sein",
    publisher: "Ministère de la Santé et de l'Hygiène publique (Burkina Faso)",
    url: "https://sante.gov.bf",
    kind: "officielle",
  },
  msd: {
    id: "msd",
    short: "Manuels MSD",
    title: "Nodules mammaires",
    publisher: "Manuels MSD",
    url: "https://www.msdmanuals.com/fr/professional/gyn%C3%A9cologie-et-obst%C3%A9trique/troubles-du-sein/nodules-mammaires",
    kind: "reference-medicale",
  },
  quotidien: {
    id: "quotidien",
    short: "Quotidien du Médecin",
    title: "L'examen clinique des seins doit être réhabilité",
    publisher: "Le Quotidien du Médecin",
    url: "https://cardiologie.lequotidiendumedecin.fr/specialites/cancerologie/lexamen-clinique-des-seins-doit-etre-rehabilite",
    kind: "presse",
  },
  "burkina24-or": {
    id: "burkina24-or",
    short: "Burkina24",
    title: "Cancer du sein au Burkina Faso : « Trois décès par jour », le gouvernement intensifie le dépistage",
    publisher: "Burkina24",
    url: "https://burkina24.com/2026/10/03/cancer-du-sein-au-burkina-faso-trois-deces-par-jour-le-gouvernement-intensifie-le-depistage/",
    date: "2026-10-03",
    kind: "presse",
  },
  "burkina24-mt": {
    id: "burkina24-mt",
    short: "Burkina24",
    title: "Cancer du sein : le diagnostic moléculaire par la « MammaTyper », désormais disponible au Burkina Faso",
    publisher: "Burkina24",
    url: "https://burkina24.com/2026/10/02/cancer-du-sein-le-diagnostic-moleculaire-par-la-mammatyper-desormais-disponible-au-burkina-faso/",
    date: "2026-10-02",
    kind: "presse",
  },
  "minute-mt": {
    id: "minute-mt",
    short: "Minute.bf",
    title: "Cancer du sein : le diagnostic moléculaire par la « MammaTyper », désormais disponible au Burkina Faso",
    publisher: "Minute.bf",
    url: "https://www.minute.bf/cancer-du-sein-le-diagnostic-moleculaire-par-la-mammatyper-desormais-disponible-au-burkina-faso/",
    date: "2026-10-02",
    kind: "presse",
  },
};
