import type { Intent } from "./types";

/** Image de soi, famille, couple, travail, argent et soutien. */
export const SUPPORT_VIE_INTENTS: Intent[] = [
  {
    id: "image_de_soi",
    status: "review",
    sources: ["inca-image"],
    actions: [{ label: "Voir les options", href: "/parcours" }],
    keywords: [
      "plus femme",
      "moche",
      "laide",
      "mutile*",
      "cicatrice*",
      "mastectomie*",
      "perdu mon sein",
      "sans sein",
      "mon corps",
      "image de moi",
      "me regarder",
      "miroir",
      "honte de mon corps",
    ],
    reply:
      "Ce que vous ressentez est normal : beaucoup de femmes vivent un vrai deuil de leur corps après une opération du sein, avec de la tristesse, parfois de la colère. Votre valeur ne dépend pas de votre corps, et vous avez le droit de prendre le temps. Des solutions existent, et en parler à une psychologue ou à d'autres femmes peut beaucoup aider.",
    followUps: ["Prothèse ou reconstruction", "Je me sens seule", "J'ai peur"],
  },
  {
    id: "prothese_reconstruction",
    status: "review",
    sources: ["inca-recon", "zcf"],
    keywords: [
      "prothese*",
      "reconstruction*",
      "implant*",
      "soutien gorge",
      "soutiens gorge",
      "tatouage",
      "refaire le sein",
    ],
    reply:
      "Après l'ablation d'un sein, il existe plusieurs options : une prothèse externe portée dans un soutien-gorge adapté, ou une reconstruction chirurgicale (avec un implant ou avec vos propres tissus), parfois faite en même temps que l'opération, parfois plus tard. Rien n'est obligatoire : c'est votre choix, avec l'équipe chirurgicale. Au Burkina Faso, l'association Zéro Cancer Féminin a remis des prothèses mammaires à des femmes.",
    actions: [{ label: "Voir les associations", href: "/association" }],
    followUps: ["Quelles aides existent ?", "Je ne me sens plus femme"],
  },
  {
    id: "enfants",
    status: "sourced",
    sources: ["hug", "ciusss"],
    keywords: [
      "enfant*",
      "mes enfants",
      "parler a mes enfants",
      "parler a mon enfant",
      "comment leur dire",
      "mes petits",
      "mon fils",
      "ma fille",
    ],
    reply:
      "Dire la vérité, avec des mots adaptés à l'âge, aide les enfants à comprendre sans se croire responsables. Vous pouvez nommer la maladie, expliquer où elle se trouve et que vous êtes soignée, préciser qu'on ne l'attrape pas, et répondre à leurs questions. Gardez leurs repères du quotidien : repas, histoires du soir, jeux.",
    followUps: ["Comment en parler à ma famille ?", "J'ai peur"],
  },
  {
    id: "famille",
    status: "review",
    keywords: [
      "annoncer",
      "dire a ma famille",
      "parler a ma famille",
      "famille",
      "entourage",
      "mes parents",
      "mon pere",
      "ma mere",
      "comment en parler",
      "parler de ma maladie",
      "cacher ma maladie",
    ],
    reply:
      "Choisir quand et comment en parler est votre décision. Vous pouvez commencer par une personne de confiance et dire simplement ce dont vous avez besoin : de l'écoute, une aide pour les enfants, un accompagnement aux rendez-vous. Vous n'avez pas à tout expliquer d'un coup.",
    followUps: ["Comment en parler à mes enfants ?", "Les gens sont maladroits"],
  },
  {
    id: "entourage_maladroit",
    status: "review",
    keywords: [
      "maladroit*",
      "les gens disent",
      "commentaires",
      "regards",
      "on me plaint",
      "pitie",
      "me regardent",
      "les gens sont",
    ],
    reply:
      "Les réactions de l'entourage peuvent blesser, même quand elles partent d'une bonne intention. Vous pouvez dire ce qui vous aide ou non, ou choisir de ne pas en parler. Vous n'avez pas à répondre à toutes les questions.",
    followUps: ["Je me sens seule", "Comment en parler à ma famille ?"],
  },
  {
    id: "couple",
    status: "review",
    keywords: [
      "mari",
      "epoux",
      "conjoint",
      "partenaire",
      "intimite",
      "sexualite",
      "desir",
      "couple",
      "relations intimes",
    ],
    reply:
      "La maladie et les traitements peuvent changer le désir, le rapport au corps et la vie de couple. C'est fréquent, et ce n'est pas un échec. Dire à votre partenaire ce que vous ressentez, avec vos mots, et ce dont vous avez besoin aide souvent. Si c'est difficile, une psychologue ou une conseillère peut vous accompagner, seule ou à deux.",
    followUps: ["Je ne me sens plus femme", "Je me sens seule"],
  },
  {
    id: "travail",
    status: "review",
    keywords: [
      "travail*",
      "reprendre",
      "patron",
      "employeur",
      "bureau",
      "emploi",
      "boulot",
      "reprise",
      "collegues",
    ],
    reply:
      "Reprendre le travail est un pas important, qui peut se faire progressivement. Parlez-en à votre équipe soignante pour savoir quand c'est possible et si un temps partiel ou un aménagement est envisageable. Vous décidez aussi avec qui partager votre situation au travail.",
    followUps: ["Je suis fatiguée", "Quelles aides existent ?"],
  },
  {
    id: "argent",
    status: "review",
    sources: ["sidwaya", "zcf", "sante-bf"],
    actions: [{ label: "Demander de l'aide", href: "/association" }],
    keywords: [
      "argent",
      "cout*",
      "payer",
      "aide financiere",
      "moyens",
      "transport",
      "frais",
      "gratuit*",
      "quelles aides",
      "pas les moyens",
      "aides existent",
      "aide existe",
    ],
    reply:
      "Les soins peuvent peser sur le budget. Au Burkina Faso, des annonces publiques évoquent la gratuité du dépistage dans les structures publiques, des campagnes de chirurgie gratuite et la radiothérapie pour certaines catégories : demandez au service social ou à l'accueil de votre hôpital ce qui s'applique. Des associations (Zéro Cancer Féminin, AFAC, Fondation Orange Burkina) peuvent aussi aider pour les prothèses, le transport ou les médicaments.",
    followUps: ["Parler à une association", "Prothèse ou reconstruction"],
  },
  {
    id: "associations",
    status: "review",
    sources: ["zcf", "sante-bf"],
    actions: [{ label: "Voir les associations", href: "/association" }],
    keywords: [
      "association*",
      "groupe de parole",
      "groupes de parole",
      "soutien moral",
      "visite*",
      "zero cancer feminin",
      "afac",
      "fondation orange",
    ],
    reply:
      "Des associations accompagnent les femmes au Burkina Faso : Zéro Cancer Féminin (causeries, prothèses mammaires), l'AFAC (aide financière, visites de réconfort) et la Fondation Orange Burkina (chirurgie gratuite lors de campagnes). L'onglet Association de RoseLink les présente. Confirmez toujours leurs services avant de vous déplacer.",
    followUps: ["Quelles aides existent ?", "Je me sens seule"],
  },
  {
    id: "espoir",
    status: "review",
    sources: ["who-bc"],
    keywords: [
      "espoir",
      "guerir",
      "guerison",
      "survivante*",
      "temoignage*",
      "histoires de femmes",
      "remission",
      "apres le traitement",
      "apres le cancer",
      "suivi",
    ],
    reply:
      "Je ne peux pas promettre une issue pour une personne précise, mais l'OMS rappelle que les traitements sont plus efficaces lorsqu'ils sont menés jusqu'au bout. Beaucoup de femmes traversent cette épreuve, et leurs témoignages arriveront bientôt dans RoseLink. En attendant, le soutien d'une association ou d'un groupe de parole peut vous aider.",
    followUps: ["Je me sens seule", "Parler à une association"],
  },
];